apiVersion: v1
kind: Service
metadata:
  labels:
    app: why-kubernetes
  name: why-kubernetes
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: why-kubernetes
